/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Aug 23 16:46:04 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.hibernate.beans;

import java.io.Serializable;

/**
 * A class that represents a row in the address table. 
 * You can customize the behavior of this class by editing the class, {@link Address()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractAddress 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the simple username property. */
    private java.lang.String username;

    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple sex property. */
    private java.lang.String sex;

    /** The value of the simple mobile property. */
    private java.lang.String mobile;

    /** The value of the simple email property. */
    private java.lang.String email;

    /** The value of the simple qq property. */
    private java.lang.String qq;

    /** The value of the simple company property. */
    private java.lang.String company;

    /** The value of the simple address property. */
    private java.lang.String address;

    /** The value of the simple postcode property. */
    private java.lang.String postcode;

    /**
     * Simple constructor of AbstractAddress instances.
     */
    public AbstractAddress()
    {
    }

    /**
     * Constructor of AbstractAddress instances given a simple primary key.
     * @param id
     */
    public AbstractAddress(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the username column.
     * @return java.lang.String
     */
    public java.lang.String getUsername()
    {
        return this.username;
    }

    /**
     * Set the value of the username column.
     * @param username
     */
    public void setUsername(java.lang.String username)
    {
        this.username = username;
    }

    /**
     * Return the value of the name column.
     * @return java.lang.String
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the name column.
     * @param name
     */
    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    /**
     * Return the value of the sex column.
     * @return java.lang.String
     */
    public java.lang.String getSex()
    {
        return this.sex;
    }

    /**
     * Set the value of the sex column.
     * @param sex
     */
    public void setSex(java.lang.String sex)
    {
        this.sex = sex;
    }

    /**
     * Return the value of the mobile column.
     * @return java.lang.String
     */
    public java.lang.String getMobile()
    {
        return this.mobile;
    }

    /**
     * Set the value of the mobile column.
     * @param mobile
     */
    public void setMobile(java.lang.String mobile)
    {
        this.mobile = mobile;
    }

    /**
     * Return the value of the email column.
     * @return java.lang.String
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    /**
     * Set the value of the email column.
     * @param email
     */
    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    /**
     * Return the value of the qq column.
     * @return java.lang.String
     */
    public java.lang.String getQq()
    {
        return this.qq;
    }

    /**
     * Set the value of the qq column.
     * @param qq
     */
    public void setQq(java.lang.String qq)
    {
        this.qq = qq;
    }

    /**
     * Return the value of the company column.
     * @return java.lang.String
     */
    public java.lang.String getCompany()
    {
        return this.company;
    }

    /**
     * Set the value of the company column.
     * @param company
     */
    public void setCompany(java.lang.String company)
    {
        this.company = company;
    }

    /**
     * Return the value of the address column.
     * @return java.lang.String
     */
    public java.lang.String getAddress()
    {
        return this.address;
    }

    /**
     * Set the value of the address column.
     * @param address
     */
    public void setAddress(java.lang.String address)
    {
        this.address = address;
    }

    /**
     * Return the value of the postcode column.
     * @return java.lang.String
     */
    public java.lang.String getPostcode()
    {
        return this.postcode;
    }

    /**
     * Set the value of the postcode column.
     * @param postcode
     */
    public void setPostcode(java.lang.String postcode)
    {
        this.postcode = postcode;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Address))
            return false;
        Address that = (Address) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
