/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Aug 14 18:57:22 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.hibernate.beans;

import java.io.Serializable;

/**
 * A class that represents a row in the user table. 
 * You can customize the behavior of this class by editing the class, {@link User()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUser implements Serializable {
	/** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
	private int hashValue = 0;

	/** The composite primary key value. */
	private java.lang.Integer id;

	/** The value of the simple username property. */
	private java.lang.String username;
	
	private java.lang.String userid;

	/** The value of the simple password property. */
	private java.lang.String password;

	/** The value of the simple email property. */
	private java.lang.String email;
	
	private java.lang.String telphone;
	
	private java.lang.String address;
	
	private java.lang.String job;
	
	private java.lang.String branch;
	
	private java.lang.String truename;
	
	private java.lang.String sex;
	
	private java.lang.Integer accessTime;
	
	private java.lang.String foundTime;
	
	private java.lang.String islogging;

	public java.lang.String getIslogging() {
		return islogging;
	}

	public void setIslogging(java.lang.String islogging) {
		this.islogging = islogging;
	}

	/**
	 * Simple constructor of AbstractUser instances.
	 */
	public AbstractUser() {
	}

	/**
	 * Constructor of AbstractUser instances given a simple primary key.
	 * @param id
	 */
	public AbstractUser(java.lang.Integer id) {
		this.setId(id);
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getId() {
		return id;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * @param id
	 */
	public void setId(java.lang.Integer id) {
		this.hashValue = 0;
		this.id = id;
	}

	/**
	 * Return the value of the username column.
	 * @return java.lang.String
	 */
	public java.lang.String getUsername() {
		return this.username;
	}

	/**
	 * Set the value of the username column.
	 * @param username
	 */
	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	/**
	 * Return the value of the password column.
	 * @return java.lang.String
	 */
	public java.lang.String getPassword() {
		return this.password;
	}

	/**
	 * Set the value of the password column.
	 * @param password
	 */
	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	/**
	 * Return the value of the email column.
	 * @return java.lang.String
	 */
	public java.lang.String getEmail() {
		return this.email;
	}

	/**
	 * Set the value of the email column.
	 * @param email
	 */
	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the primary key values.
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof User))
			return false;
		User that = (User) rhs;
		if (this.getId() == null || that.getId() == null)
			return false;
		return (this.getId().equals(that.getId()));
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern with
	 * the exception of array properties (these are very unlikely primary key types).
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			int idValue = this.getId() == null ? 0 : this.getId().hashCode();
			result = result * 37 + idValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}

	public java.lang.String getTelphone() {
		return telphone;
	}

	public void setTelphone(java.lang.String telphone) {
		this.telphone = telphone;
	}

	public java.lang.String getAddress() {
		return address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getJob() {
		return job;
	}

	public void setJob(java.lang.String job) {
		this.job = job;
	}

	public java.lang.String getBranch() {
		return branch;
	}

	public void setBranch(java.lang.String branch) {
		this.branch = branch;
	}

	public java.lang.String getTruename() {
		return truename;
	}

	public void setTruename(java.lang.String truename) {
		this.truename = truename;
	}

	public java.lang.String getSex() {
		return sex;
	}

	public void setSex(java.lang.String sex) {
		this.sex = sex;
	}

	public java.lang.Integer getAccessTime() {
		return accessTime;
	}

	public void setAccessTime(java.lang.Integer accessTime) {
		this.accessTime = accessTime;
	}

	public java.lang.String getFoundTime() {
		return foundTime;
	}

	public void setFoundTime(java.lang.String foundTime) {
		this.foundTime = foundTime;
	}

	public java.lang.String getUserid() {
		return userid;
	}

	public void setUserid(java.lang.String userid) {
		this.userid = userid;
	}
}
